version: "3"

services:
    graphql:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: portfolio-backend
        restart: unless-stopped
        ports:
            - 5001:5001
        env_file:
            - .env
